trigger:
- main

pool:
  name: Default

steps:
- checkout: self

- task: CmdLine@2
  displayName: "Maven Build"
  inputs:
    script: './mvnw clean compile package'
    workingDirectory: $(Build.SourcesDirectory)

- task: Docker@2
  displayName: "Docker build and upload to acr"
  inputs:
    containerRegistry: 'ado-acr'
    repository: 'demoapp'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      latest
      $(Build.BuildId)

- task: Bash@3
  displayName: "Docker image scan"
  inputs:
    script: grype demoapp:latest -o json
