---
apiVersion: v1
kind: Namespace
metadata:
  name: demoapp

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-config
  namespace: demoapp
data:
  application.properties: |
    spring.jpa.hibernate.ddl-auto=update
    spring.datasource.url=jdbc:mysql://xxxx.mysql.database.azure.com:3306/db_example
    spring.datasource.username=springuser@xxxx
    spring.datasource.password=xxxx
    spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app
  namespace: demoapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: spring-app
        image: xxxx.azurecr.io/demoapp:latest
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 8080
        env:
        - name: db_host
          value: "mysql"
        volumeMounts:
        - name: config-volume
          mountPath: /conf/application.properties
          subPath: application.properties
      volumes:
      - name: config-volume
        configMap:
          name: spring-config
      imagePullSecrets:
        - name: acrcred

---
apiVersion: v1
kind: Service
metadata:
  name: spring-app
  namespace: demoapp
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: spring-app